import type { DashboardData } from "./types";

const now = new Date();
const iso = (minutesFromNow: number) =>
  new Date(now.getTime() + minutesFromNow * 60_000).toISOString();

export function getMockDashboardData(dbError?: string): DashboardData {
  return {
    source: "demo",
    refreshedAt: new Date().toISOString(),
    ticketCounts: {
      active: 4,
      archived: 1,
      urgent: 3,
      needsAttention: 4,
      waiting: 0,
      breached: 1,
      resolved: 1,
      closed: 0,
      needsHumanTriage: 1,
      completionReviewsPending: 0,
    },
    ticketPage: {
      limit: 4,
      offset: 0,
      hasMore: false,
    },
    dbError,
    integrations: {
      jev: {
        configured: false,
        model: "jev-latest",
        triageRubricVersion: "ticket-triage-v1",
        completionRubricVersion: "ticket-completion-review-v1",
        procedureVersion: "company-ticket-completion-v1",
        customProceduresConfigured: false,
      },
    },
    metrics: [
      {
        key: "openTickets",
        label: "Open tickets",
        value: "18",
        detail: "6 waiting for owner",
        tone: "text-sky-600",
      },
      {
        key: "p1Incidents",
        label: "P1 incidents",
        value: "3",
        detail: "2 customer facing",
        tone: "text-red-600",
      },
      {
        key: "slaBreaches",
        label: "SLA breaches",
        value: "2",
        detail: "Both assigned to platform",
        tone: "text-amber-600",
      },
      {
        key: "avgAge",
        label: "Avg age",
        value: "42m",
        detail: "Down 14m from prior hour",
        tone: "text-emerald-600",
      },
    ],
    tickets: [
      {
        id: "demo-ticket-1",
        incidentId: "demo-incident-1",
        ticketNumber: "1042",
        title: "Checkout API returning 502 for paid accounts",
        description: "Customer-facing checkout failures are breaching SLA.",
        status: "in_progress",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        assignedUserId: "demo-user-1",
        assignedTeamId: "demo-team-1",
        assignee: "Maya Chen",
        team: "Platform",
        reporterEmail: "alerts@stripe-monitor.example",
        slaDueAt: iso(-8),
        createdAt: iso(-52),
        updatedAt: iso(-3),
        createdFrom: "alert_email",
        duplicateCount: 7,
        intakeAssessment: {
          status: "succeeded",
          issueType: "software",
          urgency: "critical",
          suggestedTeamId: "demo-team-1",
          suggestedTeam: "Platform",
          confidence: 0.92,
          needsHumanTriage: false,
          model: "jev-latest",
          assessedAt: iso(-51),
        },
        routingDecision: {
          priority: "P1",
          assignedTeamId: "demo-team-1",
          assignedTeam: "Platform",
          assignedUserId: "demo-user-1",
          assignedUser: "Maya Chen",
          responseDueAt: iso(-47),
          needsHumanTriage: false,
          ruleVersion: "ticket-routing-v1",
        },
        completionReview: null,
        comments: [
          {
            id: "demo-comment-1",
            ticketId: "demo-ticket-1",
            authorEmail: "maya@example.com",
            body: "Acknowledged. Checking edge function logs and checkout dependency health.",
            createdVia: "ui",
            createdAt: iso(-2),
          },
        ],
      },
      {
        id: "demo-ticket-2",
        incidentId: "demo-incident-2",
        ticketNumber: "1041",
        title: "Inbound mail parser retry rate above threshold",
        description: "Webhook parser retries crossed the route threshold.",
        status: "assigned",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        assignedUserId: "demo-user-2",
        assignedTeamId: "demo-team-2",
        assignee: "Owen Patel",
        team: "Messaging",
        reporterEmail: "ops@example.com",
        slaDueAt: iso(22),
        createdAt: iso(-80),
        updatedAt: iso(-18),
        createdFrom: "alert_email",
        duplicateCount: 4,
        intakeAssessment: {
          status: "succeeded",
          issueType: "monitoring_alert",
          urgency: "high",
          suggestedTeamId: "demo-team-2",
          suggestedTeam: "Messaging",
          confidence: 0.84,
          needsHumanTriage: false,
          model: "jev-latest",
          assessedAt: iso(-79),
        },
        routingDecision: {
          priority: "P2",
          assignedTeamId: "demo-team-2",
          assignedTeam: "Messaging",
          assignedUserId: "demo-user-2",
          assignedUser: "Owen Patel",
          responseDueAt: iso(-65),
          needsHumanTriage: false,
          ruleVersion: "ticket-routing-v1",
        },
        completionReview: null,
        comments: [],
      },
      {
        id: "demo-ticket-3",
        incidentId: "demo-incident-3",
        ticketNumber: "1040",
        title: "Duplicate suppression missed database timeout cluster",
        description: "Similar database timeout events were not collapsed into one incident.",
        status: "triaged",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        assignedUserId: null,
        assignedTeamId: "demo-team-3",
        assignee: "Unassigned",
        team: "Database",
        reporterEmail: "neon-monitor@example.com",
        slaDueAt: iso(39),
        createdAt: iso(-111),
        updatedAt: iso(-29),
        createdFrom: "alert_email",
        duplicateCount: 5,
        intakeAssessment: {
          status: "succeeded",
          issueType: "database",
          urgency: "high",
          suggestedTeamId: "demo-team-3",
          suggestedTeam: "Database",
          confidence: 0.78,
          needsHumanTriage: false,
          model: "jev-latest",
          assessedAt: iso(-110),
        },
        routingDecision: {
          priority: "P2",
          assignedTeamId: "demo-team-3",
          assignedTeam: "Database",
          assignedUserId: null,
          assignedUser: null,
          responseDueAt: iso(-96),
          needsHumanTriage: false,
          ruleVersion: "ticket-routing-v1",
        },
        completionReview: null,
        comments: [],
      },
      {
        id: "demo-ticket-4",
        incidentId: null,
        ticketNumber: "1039",
        title: "Low-confidence alert needs manual routing review",
        description: "Alert matched no high-confidence routing rule.",
        status: "new",
        priority: "P3",
        importanceScore: 18,
        urgencyScore: 17,
        assignedUserId: null,
        assignedTeamId: null,
        assignee: "Unassigned",
        team: "Unrouted",
        reporterEmail: "support@example.com",
        slaDueAt: iso(94),
        createdAt: iso(-44),
        updatedAt: iso(-44),
        createdFrom: "alert_email",
        duplicateCount: 1,
        intakeAssessment: {
          status: "succeeded",
          issueType: "other",
          urgency: "normal",
          suggestedTeamId: null,
          suggestedTeam: null,
          confidence: 0.18,
          needsHumanTriage: true,
          model: "jev-latest",
          assessedAt: iso(-43),
        },
        routingDecision: {
          priority: "P3",
          assignedTeamId: null,
          assignedTeam: null,
          assignedUserId: null,
          assignedUser: null,
          responseDueAt: iso(94),
          needsHumanTriage: true,
          ruleVersion: "ticket-routing-v1",
        },
        completionReview: null,
        comments: [],
      },
      {
        id: "demo-ticket-5",
        incidentId: null,
        ticketNumber: "1038",
        title: "Reset locked accounting workstation",
        description: "The accounting workstation was locked after repeated sign-in failures.",
        status: "resolved",
        priority: "P3",
        importanceScore: 20,
        urgencyScore: 18,
        assignedUserId: "demo-user-4",
        assignedTeamId: "demo-team-4",
        assignee: "Sam Rivera",
        team: "Security",
        reporterEmail: "finance@example.com",
        slaDueAt: iso(-180),
        createdAt: iso(-260),
        updatedAt: iso(-120),
        createdFrom: "client_email",
        duplicateCount: 0,
        intakeAssessment: {
          status: "succeeded",
          issueType: "account_access",
          urgency: "normal",
          suggestedTeamId: "demo-team-4",
          suggestedTeam: "Security",
          confidence: 0.88,
          needsHumanTriage: false,
          model: "jev-latest",
          assessedAt: iso(-259),
        },
        routingDecision: {
          priority: "P3",
          assignedTeamId: "demo-team-4",
          assignedTeam: "Security",
          assignedUserId: "demo-user-4",
          assignedUser: "Sam Rivera",
          responseDueAt: iso(-200),
          needsHumanTriage: false,
          ruleVersion: "ticket-routing-v1",
        },
        completionReview: {
          status: "succeeded",
          overallScore: 83,
          evidenceCoverage: 67,
          missingEvidenceCount: 1,
          model: "jev-latest",
          rubricVersion: "ticket-completion-review-v1",
          reviewedAt: iso(-119),
          criteria: [
            {
              id: "documentation",
              label: "Documentation complete",
              outcome: "met",
              score: 2.6,
              evidenceProbability: 0.94,
              confidence: 0.82,
            },
            {
              id: "customer_next_steps",
              label: "Customer given clear next steps",
              outcome: "met",
              score: 2.4,
              evidenceProbability: 0.88,
              confidence: 0.76,
            },
            {
              id: "verification",
              label: "Required verification evidenced",
              outcome: "missing_evidence",
              score: null,
              evidenceProbability: 0.22,
              confidence: null,
            },
          ],
        },
        comments: [
          {
            id: "demo-comment-5",
            ticketId: "demo-ticket-5",
            authorEmail: "sam@example.com",
            body: "Unlocked the workstation, reset the failed-attempt counter, and sent sign-in guidance to the customer.",
            createdVia: "ui",
            createdAt: iso(-122),
          },
        ],
      },
    ],
    incidents: [
      {
        id: "demo-incident-1",
        title: "Checkout API 502 cluster",
        status: "open",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        confidence: 0.92,
        firstSeenAt: iso(-52),
        lastSeenAt: iso(-3),
        blastCount: 7,
      },
      {
        id: "demo-incident-2",
        title: "Inbound parser retries",
        status: "monitoring",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        confidence: 0.81,
        firstSeenAt: iso(-80),
        lastSeenAt: iso(-18),
        blastCount: 4,
      },
      {
        id: "demo-incident-3",
        title: "Database timeout cluster",
        status: "open",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        confidence: 0.74,
        firstSeenAt: iso(-111),
        lastSeenAt: iso(-29),
        blastCount: 5,
      },
    ],
    teamLoad: [
      { team: "Platform", openTickets: 7, urgentTickets: 4, members: 5 },
      { team: "Messaging", openTickets: 4, urgentTickets: 1, members: 3 },
      { team: "Database", openTickets: 5, urgentTickets: 2, members: 4 },
      { team: "Security", openTickets: 2, urgentTickets: 1, members: 2 },
    ],
    teams: [
      { id: "demo-team-1", name: "Platform", members: 1, onCall: 1 },
      { id: "demo-team-2", name: "Messaging", members: 1, onCall: 1 },
      { id: "demo-team-3", name: "Database", members: 1, onCall: 1 },
      { id: "demo-team-4", name: "Security", members: 1, onCall: 1 },
    ],
    users: [
      {
        id: "demo-user-1",
        email: "maya@example.com",
        fullName: "Maya Chen",
        role: "manager",
        teamIds: ["demo-team-1"],
        onCall: true,
      },
      {
        id: "demo-user-2",
        email: "owen@example.com",
        fullName: "Owen Patel",
        role: "agent",
        teamIds: ["demo-team-2"],
        onCall: true,
      },
      {
        id: "demo-user-3",
        email: "riley@example.com",
        fullName: "Riley Gomez",
        role: "agent",
        teamIds: ["demo-team-3"],
        onCall: true,
      },
      {
        id: "demo-user-4",
        email: "sam@example.com",
        fullName: "Sam Rivera",
        role: "agent",
        teamIds: ["demo-team-4"],
        onCall: true,
      },
    ],
  };
}
