import { AlertTriangle, Clock3, Gauge, RadioTower } from "lucide-react";
import type { DashboardData } from "./types";

const now = new Date();
const iso = (minutesFromNow: number) =>
  new Date(now.getTime() + minutesFromNow * 60_000).toISOString();

export function getMockDashboardData(dbError?: string): DashboardData {
  return {
    source: "demo",
    refreshedAt: new Date().toISOString(),
    dbError,
    metrics: [
      {
        label: "Open tickets",
        value: "18",
        detail: "6 waiting for owner",
        icon: RadioTower,
        tone: "text-sky-600",
      },
      {
        label: "P1 incidents",
        value: "3",
        detail: "2 customer facing",
        icon: AlertTriangle,
        tone: "text-red-600",
      },
      {
        label: "SLA breaches",
        value: "2",
        detail: "Both assigned to platform",
        icon: Clock3,
        tone: "text-amber-600",
      },
      {
        label: "Avg age",
        value: "42m",
        detail: "Down 14m from prior hour",
        icon: Gauge,
        tone: "text-emerald-600",
      },
    ],
    tickets: [
      {
        id: "demo-ticket-1",
        ticketNumber: "1042",
        title: "Checkout API returning 502 for paid accounts",
        status: "in_progress",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        assignee: "Maya Chen",
        team: "Platform",
        reporterEmail: "alerts@stripe-monitor.example",
        slaDueAt: iso(-8),
        updatedAt: iso(-3),
        duplicateCount: 7,
      },
      {
        id: "demo-ticket-2",
        ticketNumber: "1041",
        title: "Inbound mail parser retry rate above threshold",
        status: "assigned",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        assignee: "Owen Patel",
        team: "Messaging",
        reporterEmail: "ops@example.com",
        slaDueAt: iso(22),
        updatedAt: iso(-18),
        duplicateCount: 4,
      },
      {
        id: "demo-ticket-3",
        ticketNumber: "1040",
        title: "Duplicate suppression missed database timeout cluster",
        status: "triaged",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        assignee: "Unassigned",
        team: "Database",
        reporterEmail: "neon-monitor@example.com",
        slaDueAt: iso(39),
        updatedAt: iso(-29),
        duplicateCount: 5,
      },
      {
        id: "demo-ticket-4",
        ticketNumber: "1039",
        title: "Low-confidence alert needs manual routing review",
        status: "new",
        priority: "P3",
        importanceScore: 18,
        urgencyScore: 17,
        assignee: "Unassigned",
        team: "Unrouted",
        reporterEmail: "support@example.com",
        slaDueAt: iso(94),
        updatedAt: iso(-44),
        duplicateCount: 1,
      },
    ],
    incidents: [
      {
        id: "demo-incident-1",
        title: "Checkout API 502 cluster",
        status: "open",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        confidence: 0.92,
        firstSeenAt: iso(-52),
        lastSeenAt: iso(-3),
        blastCount: 7,
      },
      {
        id: "demo-incident-2",
        title: "Inbound parser retries",
        status: "monitoring",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        confidence: 0.81,
        firstSeenAt: iso(-80),
        lastSeenAt: iso(-18),
        blastCount: 4,
      },
      {
        id: "demo-incident-3",
        title: "Database timeout cluster",
        status: "open",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        confidence: 0.74,
        firstSeenAt: iso(-111),
        lastSeenAt: iso(-29),
        blastCount: 5,
      },
    ],
    teamLoad: [
      { team: "Platform", openTickets: 7, urgentTickets: 4, members: 5 },
      { team: "Messaging", openTickets: 4, urgentTickets: 1, members: 3 },
      { team: "Database", openTickets: 5, urgentTickets: 2, members: 4 },
      { team: "Security", openTickets: 2, urgentTickets: 1, members: 2 },
    ],
  };
}
