import type { DashboardData } from "./types";

const now = new Date();
const iso = (minutesFromNow: number) =>
  new Date(now.getTime() + minutesFromNow * 60_000).toISOString();

export function getMockDashboardData(dbError?: string): DashboardData {
  return {
    source: "demo",
    refreshedAt: new Date().toISOString(),
    dbError,
    metrics: [
      {
        key: "openTickets",
        label: "Open tickets",
        value: "18",
        detail: "6 waiting for owner",
        tone: "text-sky-600",
      },
      {
        key: "p1Incidents",
        label: "P1 incidents",
        value: "3",
        detail: "2 customer facing",
        tone: "text-red-600",
      },
      {
        key: "slaBreaches",
        label: "SLA breaches",
        value: "2",
        detail: "Both assigned to platform",
        tone: "text-amber-600",
      },
      {
        key: "avgAge",
        label: "Avg age",
        value: "42m",
        detail: "Down 14m from prior hour",
        tone: "text-emerald-600",
      },
    ],
    tickets: [
      {
        id: "demo-ticket-1",
        incidentId: "demo-incident-1",
        ticketNumber: "1042",
        title: "Checkout API returning 502 for paid accounts",
        description: "Customer-facing checkout failures are breaching SLA.",
        status: "in_progress",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        assignedUserId: "demo-user-1",
        assignedTeamId: "demo-team-1",
        assignee: "Maya Chen",
        team: "Platform",
        reporterEmail: "alerts@stripe-monitor.example",
        slaDueAt: iso(-8),
        createdAt: iso(-52),
        updatedAt: iso(-3),
        createdFrom: "alert_email",
        duplicateCount: 7,
        comments: [
          {
            id: "demo-comment-1",
            ticketId: "demo-ticket-1",
            authorEmail: "maya@example.com",
            body: "Acknowledged. Checking edge function logs and checkout dependency health.",
            createdVia: "ui",
            createdAt: iso(-2),
          },
        ],
      },
      {
        id: "demo-ticket-2",
        incidentId: "demo-incident-2",
        ticketNumber: "1041",
        title: "Inbound mail parser retry rate above threshold",
        description: "Webhook parser retries crossed the route threshold.",
        status: "assigned",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        assignedUserId: "demo-user-2",
        assignedTeamId: "demo-team-2",
        assignee: "Owen Patel",
        team: "Messaging",
        reporterEmail: "ops@example.com",
        slaDueAt: iso(22),
        createdAt: iso(-80),
        updatedAt: iso(-18),
        createdFrom: "alert_email",
        duplicateCount: 4,
        comments: [],
      },
      {
        id: "demo-ticket-3",
        incidentId: "demo-incident-3",
        ticketNumber: "1040",
        title: "Duplicate suppression missed database timeout cluster",
        description: "Similar database timeout events were not collapsed into one incident.",
        status: "triaged",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        assignedUserId: null,
        assignedTeamId: "demo-team-3",
        assignee: "Unassigned",
        team: "Database",
        reporterEmail: "neon-monitor@example.com",
        slaDueAt: iso(39),
        createdAt: iso(-111),
        updatedAt: iso(-29),
        createdFrom: "alert_email",
        duplicateCount: 5,
        comments: [],
      },
      {
        id: "demo-ticket-4",
        incidentId: null,
        ticketNumber: "1039",
        title: "Low-confidence alert needs manual routing review",
        description: "Alert matched no high-confidence routing rule.",
        status: "new",
        priority: "P3",
        importanceScore: 18,
        urgencyScore: 17,
        assignedUserId: null,
        assignedTeamId: null,
        assignee: "Unassigned",
        team: "Unrouted",
        reporterEmail: "support@example.com",
        slaDueAt: iso(94),
        createdAt: iso(-44),
        updatedAt: iso(-44),
        createdFrom: "alert_email",
        duplicateCount: 1,
        comments: [],
      },
    ],
    incidents: [
      {
        id: "demo-incident-1",
        title: "Checkout API 502 cluster",
        status: "open",
        priority: "P1",
        importanceScore: 45,
        urgencyScore: 42,
        confidence: 0.92,
        firstSeenAt: iso(-52),
        lastSeenAt: iso(-3),
        blastCount: 7,
      },
      {
        id: "demo-incident-2",
        title: "Inbound parser retries",
        status: "monitoring",
        priority: "P2",
        importanceScore: 35,
        urgencyScore: 28,
        confidence: 0.81,
        firstSeenAt: iso(-80),
        lastSeenAt: iso(-18),
        blastCount: 4,
      },
      {
        id: "demo-incident-3",
        title: "Database timeout cluster",
        status: "open",
        priority: "P2",
        importanceScore: 31,
        urgencyScore: 31,
        confidence: 0.74,
        firstSeenAt: iso(-111),
        lastSeenAt: iso(-29),
        blastCount: 5,
      },
    ],
    teamLoad: [
      { team: "Platform", openTickets: 7, urgentTickets: 4, members: 5 },
      { team: "Messaging", openTickets: 4, urgentTickets: 1, members: 3 },
      { team: "Database", openTickets: 5, urgentTickets: 2, members: 4 },
      { team: "Security", openTickets: 2, urgentTickets: 1, members: 2 },
    ],
    teams: [
      { id: "demo-team-1", name: "Platform", members: 1, onCall: 1 },
      { id: "demo-team-2", name: "Messaging", members: 1, onCall: 1 },
      { id: "demo-team-3", name: "Database", members: 1, onCall: 1 },
      { id: "demo-team-4", name: "Security", members: 1, onCall: 1 },
    ],
    users: [
      {
        id: "demo-user-1",
        email: "maya@example.com",
        fullName: "Maya Chen",
        role: "manager",
        teamIds: ["demo-team-1"],
      },
      {
        id: "demo-user-2",
        email: "owen@example.com",
        fullName: "Owen Patel",
        role: "agent",
        teamIds: ["demo-team-2"],
      },
      {
        id: "demo-user-3",
        email: "riley@example.com",
        fullName: "Riley Gomez",
        role: "agent",
        teamIds: ["demo-team-3"],
      },
      {
        id: "demo-user-4",
        email: "sam@example.com",
        fullName: "Sam Rivera",
        role: "agent",
        teamIds: ["demo-team-4"],
      },
    ],
  };
}
